name: Fetch latest spreadsheets from AZDHS

on:
  push:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron:  '* 17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Node version
      run: node --version

    - name: NPM version
      run: npm --version

    - name: Install yarn & gridsome
      run: npm install --global yarn @gridsome/cli

    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: yarn install
      run: yarn install && yarn add @gridsome/source-filesystem

    - name: Fetch latest data
      run: yarn run download:latest

    - name: Extract latest data
      run: yarn run extract:latest

    - name: Aggregate data
      run: yarn run combine

    - name: Build Gridsome site
      run: gridsome build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.

    - name: Commit and push if it changed
      run: |-
        git config user.name "Robot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push